services:
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - "8000:80"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mysql:8
    volumes:
      - type: bind
        source: "./db/my.cnf"
        target: "/etc/mysql/conf.d/my.cnf"
      - ./db/log:/var/log/mysql
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-evork}
      MYSQL_USER: ${MYSQL_USER:-evork}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    restart: unless-stopped
