// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Affiliation struct {
	ID        uint32    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Authority struct {
	ID        uint32    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Bookmark struct {
	UserID    uint32    `json:"user_id"`
	WorkID    uint32    `json:"work_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Event struct {
	ID                 uint32         `json:"id"`
	Name               string         `json:"name"`
	Password           sql.NullString `json:"password"`
	IsRequiresPassword bool           `json:"is_requires_password"`
	StartAt            sql.NullTime   `json:"start_at"`
	EndAt              sql.NullTime   `json:"end_at"`
	NeedProofreading   bool           `json:"need_proofreading"`
	IconUrl            sql.NullString `json:"icon_url"`
	Description        sql.NullString `json:"description"`
	Detail             sql.NullString `json:"detail"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type EventUserAuthority struct {
	EventID     uint32    `json:"event_id"`
	UserID      uint32    `json:"user_id"`
	AuthorityID uint32    `json:"authority_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Genre struct {
	ID        uint32    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Occupation struct {
	ID        uint32    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Technology struct {
	ID        uint32    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Tool struct {
	ID        uint32    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID                       uint32         `json:"id"`
	FirebaseUid              string         `json:"firebase_uid"`
	Email                    string         `json:"email"`
	Username                 string         `json:"username"`
	AffiliationID            uint32         `json:"affiliation_id"`
	EnrollmentYear           int32          `json:"enrollment_year"`
	GraduationYear           int32          `json:"graduation_year"`
	IsJobHuntCompleted       bool           `json:"is_job_hunt_completed"`
	SelfIntroduction         string         `json:"self_introduction"`
	IconUrl                  sql.NullString `json:"icon_url"`
	ShowProfileInPublicEvent bool           `json:"show_profile_in_public_event"`
	ShowProfileInSharedUrl   bool           `json:"show_profile_in_shared_url"`
	CreatedAt                time.Time      `json:"created_at"`
	UpdatedAt                time.Time      `json:"updated_at"`
}

type UserOccupation struct {
	UserID       uint32    `json:"user_id"`
	OccupationID uint32    `json:"occupation_id"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type UserUrl struct {
	ID        uint32    `json:"id"`
	UserID    uint32    `json:"user_id"`
	UrlName   string    `json:"url_name"`
	Url       string    `json:"url"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Work struct {
	ID        uint32    `json:"id"`
	EventID   uint32    `json:"event_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type WorkDataGenre struct {
	WorkDataID uint32    `json:"work_data_id"`
	GenreID    uint32    `json:"genre_id"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type WorkDataImage struct {
	ID         uint32    `json:"id"`
	WorkDataID uint32    `json:"work_data_id"`
	Url        string    `json:"url"`
	Order      int8      `json:"order"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type WorkDataTechnology struct {
	WorkDataID   uint32    `json:"work_data_id"`
	TechnologyID uint32    `json:"technology_id"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type WorkDataTool struct {
	WorkDataID uint32    `json:"work_data_id"`
	ToolID     uint32    `json:"tool_id"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type WorkDataUser struct {
	WorkDataID      uint32    `json:"work_data_id"`
	UserID          uint32    `json:"user_id"`
	RoleExplanation string    `json:"role_explanation"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type WorkDatum struct {
	ID               uint32         `json:"id"`
	WorkID           uint32         `json:"work_id"`
	Name             string         `json:"name"`
	Description      string         `json:"description"`
	WorkUrl          sql.NullString `json:"work_url"`
	MovieUrl         sql.NullString `json:"movie_url"`
	SystemDiagramUrl sql.NullString `json:"system_diagram_url"`
	ThumbnailUrl     sql.NullString `json:"thumbnail_url"`
	Detail           sql.NullString `json:"detail"`
	IsApproved       bool           `json:"is_approved"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}
